# Generated by Django 2.2.3 on 2019-07-21 11:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('customer_id', models.IntegerField()),
                ('product_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pricing', django.contrib.postgres.fields.jsonb.JSONField()),
                ('invoice_path', models.CharField(max_length=255, null=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
