# Generated by Django 2.2.3 on 2019-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicingtool', '0002_auto_20190721_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedInvoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_processed', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('created_by', models.IntegerField(null=True)),
            ],
        ),
    ]
