# Generated by Django 2.2.3 on 2019-07-22 10:17

from django.db import migrations, models
import django.utils.timezone
import invoicingtool.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicingtool', '0003_uploadedinvoicefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedinvoicefile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='uploadedinvoicefile',
            name='updated_at',
            field=invoicingtool.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=invoicingtool.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
