# Generated by Django 2.2.3 on 2019-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicingtool', '0004_auto_20190722_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedinvoicefile',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedinvoicefile',
            name='percentage_processed',
            field=models.IntegerField(default=0),
        ),
    ]
